[env]
_.file = '.env'

[tools]
erlang = '26.2.5.2'
elixir = '1.16.3-otp-26'
lazydocker = '0.23.3'

[plugins]
# sudo usermod -aG docker $USER
lazydocker = 'https://github.com/comdotlinux/asdf-lazydocker.git'

# to run the compose file with lazydocker:
# ```
# gui:
#   returnImmediately: true
# commandTemplates:
#   dockerCompose: "docker compose"
# logs:
#   since: ''
#   tail: 2000
# ```
# into:
#  ~/.config/lazydocker/config.yml
